name: Update Readme

on:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install
      - name: Update README
        run: yarn node index.js
      - name: Commit README
        run: |
          git config --local user.email "inho1019@naver.com"
          git config --local user.name "inho1019"
          git add .
          git commit -m "Update README.md"
          git push